""" A python script that sends e-mail reminders  using data that was generated by meeting_reminder.sh bash script """


import argparse
import datetime
import email
import email.message
import logging
import smtplib
import sys


def usage():
    """Creates some print statements for better understanding"""

    print("\nInvocation:")
    print("\tsend_reminders 'date|Meeting Title|Emails'")

    return 1


def dow(date):
    """Creates dow"""

    dateobj = datetime.datetime.strptime(date, r"%d/%m/%Y")

    return dateobj.strftime("%A")


def message_template(date: str, title: str):
    """Create the message"""
    message = email.message.EmailMessage()
    weekday = dow(date)
    message["Subject"] = f'Meeting reminder: "{title}"'
    message.set_content(
        f"""
Hi all!

This is a quick mail to remind you all that we have a meeting about:
"{title}
the {weekday} {date}.

See you there.
"""
    )
    return message


def send_message(message, emails):
    """Create a function to send the 'message' to the designated email"""
    try:
        smtp = smtplib.SMTP("localhost")
        message["From"] = "noreply@example.com"

        for email in emails.split("."):
            del message["To"]
            message["To"] = email
            smtp.send_message(message)
        smtp.quit()
    except Exception as e:
        print(f"Error sending email: {e}", file=sys.stderr)


def parse_arguments():
    """Create parse arguments and set some types/help"""

    parser = argparse.ArgumentParser(description="Send email reminders.")

    parser.add_argument("date", type=str, help='Date in the format "dd/mm/yyyy"')
    parser.add_argument("title", type=str, help="Meeting title")
    parser.add_argument("emails", type=str, help="Email addresses separated by commas")

    return parser.parse_args()


def main():
    """Main function"""

    args = parse_arguments()

    try:
        date, title, emails = args.date, args.title, args.emails

        message = message_template(date, title)
        send_message(message, emails)
        print("Successfully sent reminders to:", emails)

    except Exception as e:
        print(f"Failure to send email: {e}", file=sys.stderr)
