""" A python script that sends e-mail reminders  using data that was generated by meeting_reminder.sh bash script """


import argparse
import datetime
import email
import email.message
import logging
import smtplib
import sys

logging.basicConfig(level=logging.INFO)


def usage():
    """Creates some log statements for better understanding"""

    # print("\nInvocation:")
    # print("\tsend_reminders 'date|Meeting Title|Emails'")

    logging.error(
        "Invalid invocation. Example: send_reminders 'date|Meeting Title|Emails'"
    )

    return 1


def dow(date):
    """Creates dow"""

    dateobj = datetime.datetime.strptime(date, r"%d/%m/%Y")

    return dateobj.strftime("%A")


def message_template(date: str, title: str):
    """Create the message"""
    message = email.message.EmailMessage()
    weekday = dow(date)
    message["Subject"] = f'Meeting reminder: "{title}"'
    message.set_content(
        f"""
Hi all!

This is a quick mail to remind you all that we have a meeting about:
{title}
on {weekday}, {date}.

See you there.
"""
    )
    return message


def send_message(message, emails):
    """Create a function to send the 'message' to the designated email"""
    try:
        smtp = smtplib.SMTP("smtp.gmail.com", 587)
        smtp.starttls()
        smtp.login("hakanispir2004@gmail.com", "ywnw yeiu eusf xgxb")
        message["From"] = "noreply@example.com"

        for recipient_email in emails.split(","):
            del message["To"]
            message["To"] = recipient_email
            smtp.send_message(message)
        smtp.quit()

    except Exception as e:
        print(f"Error sending email: {e}", file=sys.stderr)


def parse_arguments():
    """Create parse arguments, set some types and add help/description options"""

    parser = argparse.ArgumentParser(description="Send email reminders.")
    parser.add_argument(
        "input_string",
        type=str,
        help='Input string in the format "date|Meeting Title|Emails"',
    )
    args = parser.parse_args()

    # Split the input string using '|' and unpack the values
    date, title, emails = args.input_string.split("|")

    return date, title, emails


def main():
    """Main function"""

    try:
        date, title, emails = parse_arguments()

        message = message_template(date, title)
        send_message(message, emails)

        logging.info("Successfully sent reminders to: %s", emails)

    except Exception as e:
        logging.error("Failure to send email due to: %s", e)


if __name__ == "__main__":
    sys.exit(main())
